spring.application.name=eazystore

server.port=8080

# H2 Database
spring.datasource.url=jdbc:h2:mem:eazystore
spring.datasource.driverClassName=org.h2.Driver
spring.sql.init.mode=embedded
spring.sql.init.data-locations=classpath:sql/data.sql
spring.sql.init.schema-locations=classpath:sql/schema.sql
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console