services:

  mysql:
    image: mysql:8.4

    container_name: mysql-db

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eazystore

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: .

    container_name: eazystore-backend

    ports:
      - "8080:8080"

    depends_on:
      - mysql

volumes:
  mysql-data: